# Site settings
title: NASH THE BAND
email: nashtheband@gmail.com
url: http://nashtheband.github.io
description: "This music should be played loud! Booking: nashtheband@gmail.com You can find us at facebook https://www.facebook.com/NASHtheband"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-light: '#f3f3f3'
  links: '#F4D03F'

# Footer settings
footer: NASH THE BAND

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/NASHtheband
  - title: twitter
    url: https://twitter.com/nashtheband
  - title: instagram
    url: https://instagram.com/nashtheband
  - title: youtube
    url: https://www.youtube.com/channel/UC1Sdya_Ja5Dtp6wCDqOrlRA

# Build settings
markdown: kramdown
permalink: pretty
